#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 10 11:35:31 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_k2_up_behav -key {Behavioral:sim_1:Functional:tb_k2_up} -tclbatch tb_k2_up.tcl -view /home/it/chip_design/commoncore/digitaldesign/cx-203-debugging-exam-main/k2-up-src-debugged/tb_k2_up_behav.wcfg -log simulate.log"
xsim tb_k2_up_behav -key {Behavioral:sim_1:Functional:tb_k2_up} -tclbatch tb_k2_up.tcl -view /home/it/chip_design/commoncore/digitaldesign/cx-203-debugging-exam-main/k2-up-src-debugged/tb_k2_up_behav.wcfg -log simulate.log

